#!/bin/bash
#
# Copyright 2010 Ericsson AB
#
#    This file is part of LTTng-UST.
#
#    LTTng-UST is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    LTTng-UST is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with LTTng-UST.  If not, see <http://www.gnu.org/licenses/>.


tests_failed=0

TESTDIR=$(dirname $0)

function simple_harness_run() {
    if ! "$TESTDIR/$@"; then
	let tests_failed=$tests_failed+1
    fi
}

./${TEST_DIR}/snprintf/run

# This testcase is currently broken, do not run.
# simple_harness_run tracepoint/run

exit 0
