#!/bin/bash

# SPDX-FileCopyrightText: 2023 EfficiOS, Inc
#
# SPDX-License-Identifier: LGPL-2.1-only

if [ "x${UST_TESTS_SRCDIR:-}" != "x" ]; then
	UTILSSH="$UST_TESTS_SRCDIR/utils/utils.sh"
else
	UTILSSH="$(dirname "$0")/../../utils/utils.sh"
fi

# shellcheck source=../utils/utils.sh
source "$UTILSSH"

"${UST_TESTS_BUILDDIR}/unit/ust-elf/ust-elf" "${UST_TESTS_SRCDIR}/unit/ust-elf"
