#!/bin/bash

TESTDIR=$(dirname $0)/..

if [ ! -x "$TESTDIR/tracepoint/tracepoint_test" ]; then
    echo "tracepoint_test executable is not present"
    exit 1
fi

source $TESTDIR/test_functions.sh
source $TESTDIR/tap.sh

starttest "Testing Tracepoints"
plan_tests 6
USTTRACE="$TESTDIR/../usttrace"

okx $USTTRACE -L $TESTDIR/tracepoint/tracepoint_test
trace_loc=$($USTTRACE -W)
trace_matches -N "probe1" -n "5" "probe = 13" $trace_loc
trace_matches -N "probe2" -n "5" "probe = 42" $trace_loc
trace_matches -N "probe3" -n "1" "probe = \"probe3\"" $trace_loc
trace_matches -N "probe4" -n "100" "probe4 = 42" $trace_loc
check_trace_logs "$trace_loc"
