#!/bin/bash

#
# The -cp path should be changed to the lttng ust agent jar file on your system
# or locally to the project. Same goes for the Java library path in order to
# find the JNI Log4j library.
#

DIR=`dirname $0`
JARFILE="liblttng-ust-agent.jar"

# If system classpath is empty, try to guess log4j location
if [ "x$CLASSPATH" = "x" ]; then
	CLASSPATH="/usr/local/share/java/log4j.jar:/usr/share/java/log4j.jar"
fi

cd $DIR

if [ -f "$DIR/.intree" ]; then
	CLASSPATH="../../../liblttng-ust-java-agent/java/$JARFILE:$CLASSPATH"
	LIBPATH="../../../liblttng-ust-java-agent/jni/log4j/.libs"
else
	CLASSPATH="/usr/local/share/java/$JARFILE:/usr/share/java/$JARFILE:$CLASSPATH"
	# Use system defined java.library.path
	#LIBPATH="/usr/local/lib:/usr/lib"
fi

java -classpath "$CLASSPATH:." -Djava.library.path="$LIBPATH" Hello

cd -
