#!/bin/bash

#
# The -cp path should be changed to the lttng ust JUL jar file on your system
# or locally to the project. Same goes for the Java library path in order to
# find the JNI JUL library.
#

DIR=`dirname $0`
JARFILE="liblttng-ust-agent.jar"

cd $DIR

if [ -f "$DIR/.intree" ]; then
	CLASSPATH="../../../liblttng-ust-java-agent/java/$JARFILE"
	LIBPATH="../../../liblttng-ust-java-agent/jni/jul/.libs"
else
	CLASSPATH="/usr/local/share/java/$JARFILE:/usr/share/java/$JARFILE"
	# Use system defined java.library.path
	#LIBPATH="/usr/local/lib:/usr/lib"
fi

java -classpath "$CLASSPATH:." -Djava.library.path="$LIBPATH" Hello

cd -
