#!/bin/sh

# SPDX-FileCopyrightText: 2023 EfficiOS, Inc
#
# SPDX-License-Identifier: MIT

# launch with: run-clock-override progname args

DIR=$(dirname "$0")
DIR=$(readlink -f "$DIR")

LTTNG_UST_CLOCK_PLUGIN="$DIR/lttng-ust-clock-override-example.so" "${@}"
